### PR TITLE
update test and integration for longform to use company.name

### PR DESCRIPTION
**Pull request by ros3bud**
@cgrayson, LGTY?

### CODE REVIEW

**Comment by cgrayson** [comment]
Unless I've missed clarifications of the process for deprecating fields (see  [fields issue 34](https://github.com/activeprospect/leadconduit-fields/issues/34)), I don't even know what should be done here. 

Simple replacement of `company` by `company.name` may break existing flows. In other deprecation cases we're continuing to set both the old and the new, but in this case that's impossible. I'm not even sure how this transition could be managed, unless no flows use `company` now, or unless the release of this change and flow changes are made simultaneously. 

@alexkwolfe, thoughts?

**Comment by alexkwolfe** [comment]
I'm not sure what the exact behavior will be if these fields co-exist. I'd need to investigate that before proceeding with a plan to transition from one field name to another.

One possibility that comes to mind is to add mappings for `company` to `company.name` on all flows that use `company` currently.

**Comment by ros3bud** [comment]
@alexkwolfe, do you want me to move forward with adding the mappings? And if so, can we do one together so I can see exactly what you mean?

**Comment by alexkwolfe** [comment]
@cgrayson, in your comment you said "In other deprecation cases we're continuing to set both the old and the new, but in this case that's impossible". Why is that impossible in this case?

**Comment by alexkwolfe** [comment]
@cgrayson, never mind. I see now.

**Pull request closed without merging**
